module.exports = {
  User: require('./User'),
  School: require('./School'),
  Student: require('./Student'),
  Teacher: require('./Teacher'),
  Parent: require('./Parent'),
  Accountant: require('./Accountant'),
  Department: require('./Department'),
  Class: require('./Class'),
  Subject: require('./Subject'),
  Timetable: require('./Timetable'),
  StudentAttendance: require('./StudentAttendance'),
  TeacherAttendance: require('./TeacherAttendance'),
  Examination: require('./Examination'),
  Result: require('./Result'),
  FeeStructure: require('./FeeStructure'),
  FeeChallan: require('./FeeChallan'),
  Payment: require('./Payment'),
  Salary: require('./Salary'),
  Leave: require('./Leave'),
  Assignment: require('./Assignment'),
  Conversation: require('./Conversation'),
  Message: require('./Message'),
  Notification: require('./Notification'),
  AuditLog: require('./AuditLog'),
};
